---
- hosts: ntp
  become: true
  tasks:

    - name: Update Operation system
      package:
        name: '*'
        state: latest

    - name: Copy line the chrony configuration
      lineinfile:
        path: /etc/chrony.conf
        regexp: '{{item.regexp}}'
        line: '{{item.line}}'
        backrefs: yes
      with_items:
        - {regexp: '^pool(.*)', line: 'server sth1.ntp.se \n server sth4.ntp.se' }

    - name: Restart Chrony service
      systemd:
        name: chronyd
        state: restarted