# -*- mode: ruby -*-
# vi: set ft=ruby :
class VagrantPlugins::ProviderVirtualBox::Action::Network
  def dhcp_server_matches_config?(dhcp_server, config)
    true
  end
end

Vagrant.configure("2") do |config|

  config.vm.define "ntp.edu.tentixo.com" do |config|
    config.vm.hostname = "ntp.edu.tentixo.com"
    config.vm.box = "generic/rhel8"
    config.vm.network "private_network", ip: "192.168.56.0"
    config.vm.box_check_update = false
  end
    config.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.gui = false
      vb.memory = "1024"
    end
    config.ssh.insert_key = false
    config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.inventory_path = "inventory"
    ansible.raw_arguments = ["-vvv", "--flush-cache"
	]
    end
end
