#This line is responsible for the name of the configuration and version vagrant.
Vagrant.configure("2") do |config|

  config.vm.define "ntp.edu.tentixo.com" do |config|            #Description of server name and config name
    config.vm.hostname = "ntp.edu.tentixo.com"                  #Hostname
    config.vm.box = "generic/rhel8"                             #The image that the vagrant will use
    config.vm.network "private_network", ip: "192.168.56.2"     #Description of the network type, specifying the ip of the machine
    config.vm.box_check_update = false                          #Prohibiting checking for updates

  end

    config.vm.provider "virtualbox" do |vb|                     #Provider selection and its config
      vb.cpus = 1                                               #Count of cpu for using VM
      vb.gui = false                                            #Without gui
      vb.memory = "1024"                                        #According memory for using VM
      
    end

    config.ssh.insert_key = false                               #Vagrant will not automatically add a keypair to the guest
    config.vm.provision :ansible do |ansible|                   #Run Ansible from the Vagrant Host
      ansible.playbook = "playbook.yml"                         #Path to playbook.yml
      ansible.inventory_path = "inventory"                      #Path to inventory
      ansible.raw_arguments = ["-vvv", "--flush-cache"
	    ]                                                         #Array with ansible_arguments for debug

    end

end
